<?php

namespace EnquisaBundle\Repository;

/**
 * EnquisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquisaRepository extends \Doctrine\ORM\EntityRepository
{
    // TODO: proba de consulta
    public function getEnquisas()
    {
        return $this->createQueryBuilder('e')
            ->addSelect('r')
            ->join('e.respostas', 'r')
            ->addSelect('o')
            ->join('r.opcion', 'o')
            ->addSelect('p')
            ->join('o.pregunta', 'p')

            ->orderBy('p.orde')
            ->getQuery()
            ->getArrayResult();
    }
}
