<?php

namespace EnquisaBundle\Repository;

/**
 * EnquisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquisaRepository extends \Doctrine\ORM\EntityRepository
{
}
