<?php

namespace EnquisaBundle\Repository;

/**
 * RestauranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestauranteRepository extends \Doctrine\ORM\EntityRepository
{
}
