enquisa_enquisa:
    resource: "@EnquisaBundle/Controller/EnquisaController.php"
    type:     annotation

enquisa_pregunta:
    resource: "@EnquisaBundle/Controller/PreguntaController.php"
    type:     annotation

enquisa_restaurante:
    resource: "@EnquisaBundle/Controller/RestauranteController.php"
    type:     annotation

enquisa:
    resource: "@EnquisaBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"